version: '3.7'
services:
  jenkins:
    image: jenkins-alab:0.1
    build:
      context: ./jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
    container_name: jenkins
    volumes:
      - ./jenkins/jobs:/usr/share/jenkins/ref/jobs
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
